### ISSUE TITLE
lede固件无法使用

### ISSUE THREAD

**Issue by Anyfc** [AlexZhuo/luci-app-haproxy-tcp#1]
网件4300 lede自编译固件，luci界面下无法启用haproxy，
命令行下 /etc/init.d/haproxy start  可以运行haproxy，但是无法和最新版shadowsocks 3.0.2版本的配合使用。

**Comment by Typhonling** [comment]
同4300 lede，只不过我这边编译都没过，应该是从下面这行开始：
cc1: note: someone does not honour COPTS correctly, passed 0 times
lua.c:80:31: fatal error: readline/readline.h: No such file or directory
compilation terminated.
<builtin>: recipe for target 'lua.o' failed
make[5]: *** [lua.o] Error 1
make[5]: Leaving directory '/root/lede-sdk-17.01.0-ar71xx-nand_gcc-5.4.0_musl-1.1.16.Linux-x86_64/build_dir/target-mips_24kc_musl-1.1.16/haproxy-ssl/haproxy-1.7.2/lua-5.3.3/src'
Makefile:110: recipe for target 'linux' failed
make[4]: *** [linux] Error 2
make[4]: Leaving directory '/root/lede-sdk-17.01.0-ar71xx-nand_gcc-5.4.0_musl-1.1.16.Linux-x86_64/build_dir/target-mips_24kc_musl-1.1.16/haproxy-ssl/haproxy-1.7.2/lua-5.3.3/src'
Makefile:55: recipe for target 'linux' failed
make[3]: *** [linux] Error 2
make[3]: Leaving directory '/root/lede-sdk-17.01.0-ar71xx-nand_gcc-5.4.0_musl-1.1.16.Linux-x86_64/build_dir/target-mips_24kc_musl-1.1.16/haproxy-ssl/haproxy-1.7.2/lua-5.3.3'
Makefile:180: recipe for target '/root/lede-sdk-17.01.0-ar71xx-nand_gcc-5.4.0_musl-1.1.16.Linux-x86_64/build_dir/target-mips_24kc_musl-1.1.16/haproxy-ssl/haproxy-1.7.2/.built' failed
make[2]: *** [/root/lede-sdk-17.01.0-ar71xx-nand_gcc-5.4.0_musl-1.1.16.Linux-x86_64/build_dir/target-mips_24kc_musl-1.1.16/haproxy-ssl/haproxy-1.7.2/.built] Error 2
make[2]: Leaving directory '/root/lede-sdk-17.01.0-ar71xx-nand_gcc-5.4.0_musl-1.1.16.Linux-x86_64/package/feeds/packages/net/haproxy'
package/Makefile:105: recipe for target 'package/feeds/packages/net/haproxy/compile' failed
make[1]: *** [package/feeds/packages/net/haproxy/compile] Error 2
make[1]: Leaving directory '/root/lede-sdk-17.01.0-ar71xx-nand_gcc-5.4.0_musl-1.1.16.Linux-x86_64'
/root/lede-sdk-17.01.0-ar71xx-nand_gcc-5.4.0_musl-1.1.16.Linux-x86_64/include/toplevel.mk:190: recipe for target 'package/luci-app-haproxy-tcp/compile' failed
make: *** [package/luci-app-haproxy-tcp/compile] Error 2

**Comment by Typhonling** [comment]
编译问题已搞定。
运行./haproxy_init.sh报错如下：

root@LEDE:/etc# ./haproxy_init.sh
luci for haproxy
./haproxy_init.sh: local: line 104: not in a function

stopping haproxy
sh: can't kill pid 4584: No such process
cp: can't stat '/etc/haproxy_backup': No such file or directory

**Comment by Anyfc** [comment]
root@LEDE:/etc# ./haproxy_init.sh
luci for haproxy
./haproxy_init.sh: local: line 112: not in a function

stopping haproxy
cat: can't open '/var/run/haproxy.pid': No such file or directory
sh: you need to specify whom to kill

**Comment by Anyfc** [comment]
感谢更新，网件4300 lede测试可用
